# -*- coding: utf-8 -*-
"""Ai Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WUx9E0K7_VTqtHZv-WMT3E91V437wjB5
"""

class SimpleAIAgent:
    def __init__(self):
        self.knowledge = {
            "hello": "Hi there! How can I help you?",
            "bye": "Goodbye!",
            "how are you": "I'm an AI, I am always good.",
            "name": "I'm a simple AI agent."
        }

    def respond(self, user_input):
        user_input = user_input.lower()
        for key in self.knowledge:
            if key in user_input:
                return self.knowledge[key]
        return "Sorry, I don't understand that."

if __name__ == "__main__":
    agent = SimpleAIAgent()
    while True:
        user_input = input("You: ")
        if user_input.lower() == "exit":
            print("AI: Goodbye!")
            break
        response = agent.respond(user_input)
        print("AI:", response)